language:
  node_js
node_js:
  - "node"
install:
  - npm install
  - npm install -g codecov
script:
  - npm test
  - codecov
# after_success:
#   - ./bin/codecov -e TRAVIS_NODE_VERSION -f coverage/coverage.json